### ISSUE TITLE
Custom snowdreamtech/frps

### ISSUE THREAD

**Issue by Bigangle1** [chenxudong2020/aliyun_docker#10]
{  
    
 
      "dockers":"snowdreamtech/frps"
                 
          
      
    
}

**Comment by happytrudy** [comment]
Bigangle1 您好.
您自定义的docker转存已完成. 请前往下面的 URL 查看详细信息.
> https://github.com/chenxudong2020/aliyun_docker/actions/runs/5168504027
转存之后的docker仓库路径：
 registry.cn-hangzhou.aliyuncs.com/dubux/snowdreamtech.frps
----
