### ISSUE TITLE
Custom qinglong

### ISSUE THREAD

**Issue by funkmm992** [chenxudong2020/aliyun_docker#11]
{  
    
 
      "dockers":"qinglong"
                 
          
      
    
}

**Comment by happytrudy** [comment]
funkmm992 您好.
您自定义的docker转存失败. 请前往下面的 URL 查看详细信息对body进行修改并请重新触发编译(Close & Reopen).
> https://github.com/chenxudong2020/aliyun_docker/actions/runs/5227541582

**Comment by happytrudy** [comment]
暂时没时间处理，关闭issue
