### ISSUE TITLE
Custom whyour/qinglong

### ISSUE THREAD

**Issue by funkmm992** [chenxudong2020/aliyun_docker#12]
{  
    
 
      "dockers":"whyour/qinglong"
                 
          
      
    
}

**Comment by happytrudy** [comment]
funkmm992 您好.
您自定义的docker转存已完成. 请前往下面的 URL 查看详细信息.
> https://github.com/chenxudong2020/aliyun_docker/actions/runs/5227581660
转存之后的docker仓库路径：
 registry.cn-hangzhou.aliyuncs.com/dubux/whyour.qinglong
----
