### ISSUE TITLE
Custom kms

### ISSUE THREAD

**Issue by Bigangle1** [chenxudong2020/aliyun_docker#13]
{  
    
 
      "dockers":"KMS"
                 
          
      
    
}

**Comment by happytrudy** [comment]
Bigangle1 您好.
您自定义的docker转存失败. 请前往下面的 URL 查看详细信息对body进行修改并请重新触发编译(Close & Reopen).
> https://github.com/chenxudong2020/aliyun_docker/actions/runs/5229248144

**Comment by happytrudy** [comment]
暂时没时间处理，关闭issue
