### ISSUE TITLE
Custom onething1/wxedge

### ISSUE THREAD

**Issue by Bigangle1** [chenxudong2020/aliyun_docker#9]
{  
    
 
      "dockers":"onething1/wxedge"
                 
          
      
    
}

**Comment by happytrudy** [comment]
Bigangle1 您好.
您自定义的docker转存已完成. 请前往下面的 URL 查看详细信息.
> https://github.com/chenxudong2020/aliyun_docker/actions/runs/5168447703
转存之后的docker仓库路径：
 registry.cn-hangzhou.aliyuncs.com/dubux/onething1.wxedge
----
